const [
  EMPTY_SPRITE,
  BACKGROUND_SPRITE,
  GROUND_SPRITE,
  WALL_SPRITE,
  TOP_DOOR_SPRITE,
  RIGHT_DOOR_SPRITE,
  BOTTOM_DOOR_SPRITE,
  LEFT_DOOR_SPRITE,
  WALL_TOP_SPRITE,
  PLAYER_SPRITE,
  PLAYER_DIALOG_SPRITE,
  KING_SPRITE,
  KING_DIALOG_SPRITE,
  JOHN_SPRITE,
  JOHN_DIALOG_SPRITE,
  MONSTER_SPRITE,
  BULLET_SPRITE,
  BULLET_SPRITE_ENEMY,
  BULLET_SPRITE_FOLLOW,
  // MONSTER_SPRITE_BOSS,
] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

const [DOOR_TOP, DOOR_RIGHT, DOOR_BOTTOM, DOOR_LEFT] = [0, 1, 2, 3]

const [
  LAYER_BACKGROUND,
  LAYER_GROUND,
  LAYER_OBSTACLES,
  LAYER_ITEMS,
  LAYER_OBJECTS,
  LAYER_WALLTOP,
] = [0, 1, 2, 3, 4, 5]

const [LAYER_TYPE_TILE, LAYER_TYPE_OBJECT] = [0, 1]

const [
  RENDERER_LAYER_BACKGROUND,
  RENDERER_LAYER_MAIN,
  RENDERER_LAYER_FOREGROUND,
  RENDERER_LAYER_TEXT,
] = [0, 1, 2, 3]

const [KEY_UP, KEY_DOWN, KEY_LEFT, KEY_RIGHT, KEY_ENTER, KEY_SPACE] = [
  0,
  1,
  2,
  3,
  4,
  5,
]

const [BATTLE_FIELD_INCIDENT] = [1]

const [
  GAME_OBJ_WIDTH_XS,
  GAME_OBJ_WIDTH_S,
  GAME_OBJ_WIDTH_M,
  GAME_OBJ_WIDTH_L,
  GAME_OBJ_WIDTH_XL,
] = [0, 1, 2, 3, 4]

const [
  GAME_OBJ_HEIGHT_XS,
  GAME_OBJ_HEIGHT_S,
  GAME_OBJ_HEIGHT_M,
  GAME_OBJ_HEIGHT_L,
  GAME_OBJ_HEIGHT_XL,
] = [0, 1, 2, 3, 4]
