const [
  EMPTY_SPRITE,
  BACKGROUND_SPRITE,
  GROUND_SPRITE,
  WALL_SPRITE,
  TOP_DOOR_SPRITE,
  RIGHT_DOOR_SPRITE,
  BOTTOM_DOOR_SPRITE,
  LEFT_DOOR_SPRITE,
  WALL_TOP_SPRITE,
  PLAYER_SPRITE,
] = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

const [DOOR_TOP, DOOR_RIGHT, DOOR_BOTTOM, DOOR_LEFT] = [0, 1, 2, 3]

const [
  LAYER_BACKGROUND,
  LAYER_GROUND,
  LAYER_OBSTACLES,
  LAYER_ITEMS,
  LAYER_OBJECTS,
  LAYER_WALLTOP,
] = [0, 1, 2, 3, 4, 5]

const [LAYER_TYPE_TILE, LAYER_TYPE_OBJECT] = [0, 1]

const [
  RENDERER_LAYER_BACKGROUND,
  RENDERER_LAYER_MAIN,
  RENDERER_LAYER_FOREGROUND,
] = [0, 1, 2]
